# Generated by Django 5.2.12 on 2026-03-07 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('year', models.PositiveIntegerField()),
                ('start_month', models.PositiveSmallIntegerField(default=3)),
                ('daily_interest_rate', models.DecimalField(decimal_places=6, default=0.000967, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', 'name'],
                'unique_together': {('name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PaymentDayRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('month', models.PositiveSmallIntegerField()),
                ('payment_date', models.DateField()),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_rules', to='dashboard.scenario')),
            ],
            options={
                'ordering': ['month', 'label'],
                'unique_together': {('scenario', 'label', 'month')},
            },
        ),
        migrations.CreateModel(
            name='IncomeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('source_tag', models.CharField(default='excel', max_length=100)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_entries', to='dashboard.scenario')),
            ],
            options={
                'ordering': ['entry_date'],
                'indexes': [models.Index(fields=['scenario', 'entry_date'], name='dashboard_i_scenari_f7e9a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_label', models.CharField(max_length=255)),
                ('financial_code', models.CharField(blank=True, max_length=120)),
                ('purchase_order', models.CharField(blank=True, max_length=120)),
                ('nueva_clasificacion', models.CharField(blank=True, max_length=255)),
                ('clasif_cash', models.CharField(blank=True, max_length=255)),
                ('source_tag', models.CharField(default='excel', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='dashboard.provider')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='dashboard.scenario')),
            ],
            options={
                'ordering': ['payment_date', '-amount'],
                'indexes': [models.Index(fields=['scenario', 'year', 'month'], name='dashboard_e_scenari_49245b_idx'), models.Index(fields=['provider', 'payment_date'], name='dashboard_e_provide_643139_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projection_date', models.DateField()),
                ('caja_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('gastos_proyectados_excel', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('ingresos_financieros_excel', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('rescate_fci', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('interes_diario_excel', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('inversiones_fci', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('intereses_acumulados', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('intereses_recuperado', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_excel', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_projections', to='dashboard.scenario')),
            ],
            options={
                'ordering': ['projection_date'],
                'unique_together': {('scenario', 'projection_date')},
            },
        ),
    ]
