# Generated by Django 5.2.12 on 2026-03-17 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_investmentdailysnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentDailyFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['snapshot', 'label'],
            },
        ),
        migrations.RenameIndex(
            model_name='fundcuotapartehistory',
            new_name='dashboard_f_fund_na_7785f3_idx',
            old_name='dashboard_fund_name_653a94_idx',
        ),
        migrations.AddField(
            model_name='investmentdailyflow',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='dashboard.investmentdailysnapshot'),
        ),
        migrations.AlterUniqueTogether(
            name='investmentdailyflow',
            unique_together={('snapshot', 'label')},
        ),
    ]
