# Generated by Django 5.2.1 on 2026-03-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_investmentdailyflow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeentry',
            name='account',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='incomeentry',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='incomeentry',
            name='classification',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='incomeentry',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='incomeentry',
            name='remarks',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
